FROM python:3
MAINTAINER Haibin <haibin.li@newtouch.cn>

RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list
COPY ./requirements/deb_requirements.txt deb_requirements.txt
COPY ./requirements/pip_requirements.txt pip_requirements.txt

RUN apt-get update
RUN apt-get install -y $(cat deb_requirements.txt)
RUN pip install -r pip_requirements.txt -i https://pypi.doubanio.com/simple --no-cache
